server:
  port: 5566

spring:
  application.name: springbootDemo
#  profiles.active: dev
  http.encoding.charset: UTF-8 # the encoding of HTTP requests/responses
  http.encoding.enabled: true # enable http encoding support
  http.encoding.force: true # force the configured encoding

#启用 shutdown endpoint的HTTP访问
endpoints.shutdown.enabled: true
#不需要用户名密码验证
endpoints.shutdown.sensitive: false